
[uni4E1F]
target = 0x4E1F  # 丟
codes = [
    0x4E1F,  # 丟
    0x4E22,  # 丢
]

[uni5024]
target = 0x5024  # 値
codes = [
    0x5024,  # 値
    0x503C,  # 值
]

[uni5036]
target = 0x5036  # 倶
codes = [
    0x4FF1,  # 俱
    0x5036,  # 倶
]

[uni50DE]
target = 0x50DE  # 僞
codes = [
    0x507D,  # 偽
    0x50DE,  # 僞
]

[uni52FB]
target = 0x52FB  # 勻
codes = [
    0x52FB,  # 勻
    0x5300,  # 匀
]

[uni543F]
target = 0x543F  # 吿
codes = [
    0x543F,  # 吿
    0x544A,  # 告
]

[uni5861]
target = 0x5861  # 塡
codes = [
    0x5861,  # 塡
    0x586B,  # 填
]

[uni59F8]
target = 0x59F8  # 姸
codes = [
    0x598D,  # 妍
    0x59F8,  # 姸
]

[uni5ABC]
target = 0x5ABC  # 媼
codes = [
    0x5AAA,  # 媪
    0x5ABC,  # 媼
]

[uni5B76]
target = 0x5B76  # 孶
codes = [
    0x5B73,  # 孳
    0x5B76,  # 孶
]

[uni5C19]
target = 0x5C19  # 尙
codes = [
    0x5C19,  # 尙
    0x5C1A,  # 尚
]

[uni5DD3]
target = 0x5DD3  # 巓
codes = [
    0x5DD3,  # 巓
    0x5DD4,  # 巔
]

[uni613C]
target = 0x613C  # 愼
codes = [
    0x613C,  # 愼
    0x614E,  # 慎
]

[uni614D]
target = 0x614D  # 慍
codes = [
    0x6120,  # 愠
    0x614D,  # 慍
]

[uni6435]
target = 0x6435  # 搵
codes = [
    0x63FE,  # 揾
    0x6435,  # 搵
]

[uni654E]
target = 0x654E  # 敎
codes = [
    0x654E,  # 敎
    0x6559,  # 教
]

[uni67B4]
target = 0x67B4  # 枴
codes = [
    0x67B4,  # 枴
    0x67FA,  # 柺
]

[uni67FB]
target = 0x67FB  # 査
codes = [
    0x67E5,  # 查
    0x67FB,  # 査
]

[uni69B2]
target = 0x69B2  # 榲
codes = [
    0x6985,  # 榅
    0x69B2,  # 榲
]

[uni6C33]
target = 0x6C33  # 氳
codes = [
    0x6C32,  # 氲
    0x6C33,  # 氳
]

[uni6DF8]
target = 0x6DF8  # 淸
codes = [
    0x6DF8,  # 淸
    0x6E05,  # 清
]

[uni6EAB]
target = 0x6EAB  # 溫
codes = [
    0x6E29,  # 温
    0x6EAB,  # 溫
]

[uni7155]
target = 0x7155  # 煕
codes = [
    0x7155,  # 煕
    0x7199,  # 熙
]

[uni7185]
target = 0x7185  # 熅
codes = [
    0x7174,  # 煴
    0x7185,  # 熅
]

[uni7232]
target = 0x7232  # 爲
codes = [
    0x70BA,  # 為
    0x7232,  # 爲
]

[uni771E]
target = 0x771E  # 眞
codes = [
    0x771E,  # 眞
    0x771F,  # 真
]

[uni784F]
target = 0x784F  # 硏
codes = [
    0x7814,  # 研
    0x784F,  # 硏
]

[uni7DD6]
target = 0x7DD6  # 緖
codes = [
    0x7DD2,  # 緒
    0x7DD6,  # 緖
]

[uni7E15]
target = 0x7E15  # 縕
codes = [
    0x7DFC,  # 緼
    0x7E15,  # 縕
]

[uni8183]
target = 0x8183  # 膃
codes = [
    0x817D,  # 腽
    0x8183,  # 膃
]

[uni8288]
target = 0x8288  # 芈
codes = [
    0x7F8B,  # 羋
    0x8288,  # 芈
]

[uni8495]
target = 0x8495  # 蒕
codes = [
    0x8480,  # 蒀
    0x8495,  # 蒕
]

[uni8580]
target = 0x8580  # 薀
codes = [
    0x8570,  # 蕰
    0x8580,  # 薀
]

[uni860A]
target = 0x860A  # 蘊
codes = [
    0x85F4,  # 藴
    0x860A,  # 蘊
]

[uni8F40]
target = 0x8F40  # 轀
codes = [
    0x8F3C,  # 輼
    0x8F40,  # 轀
]

[uni9109]
target = 0x9109  # 鄉
codes = [
    0x90F7,  # 郷
    0x9109,  # 鄉
]

[uni919E]
target = 0x919E  # 醞
codes = [
    0x9196,  # 醖
    0x919E,  # 醞
]

[uni93AD]
target = 0x93AD  # 鎭
codes = [
    0x93AD,  # 鎭
    0x93AE,  # 鎮
]

[uni9751]
target = 0x9751  # 靑
codes = [
    0x9751,  # 靑
    0x9752,  # 青
]

[uni985A]
target = 0x985A  # 顚
codes = [
    0x985A,  # 顚
    0x985B,  # 顛
]

[uni98EE]
target = 0x98EE  # 飮
codes = [
    0x98EE,  # 飮
    0x98F2,  # 飲
]

[uni9C2E]
target = 0x9C2E  # 鰮
codes = [
    0x9C1B,  # 鰛
    0x9C2E,  # 鰮
]
