name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        font-size: [10, 12, 16]
        width-mode: [monospaced, proportional]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install pip --upgrade
        python -m pip install -r requirements.txt
    - name: Build
      run: python -m scripts.tools.release_${{ matrix.font-size }}px_${{ matrix.width-mode }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./build/releases/ark-pixel-font-inherited-${{ matrix.font-size }}px-${{ matrix.width-mode }}-*.zip
