name: Release

on:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: write
    strategy:
      matrix:
        font-size: [10, 12, 16]
        width-mode: [monospaced, proportional]
        font-format: [otf, ttf, woff2, bdf, pcf]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Build
        run: python -m tools.cli --cleanup --font-sizes ${{ matrix.font-size }} --width-modes ${{ matrix.width-mode }} --font-formats ${{ matrix.font-format }} --release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/releases/*.zip
